service: aws-java-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java12

package:
  artifact: build/distributions/home-assignement.zip

functions:
  currentTime:
    handler: home.assignement.StreamLambdaHandler
    events:
      - http:
          path: ping
          method: get