service: twitter-median-lengths

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java12

package:
  artifact: build/distributions/twitter-median-length.zip

functions:
  currentTime:
    handler: twitter.median.length.StreamLambdaHandler
    events:
      - http:
          path: ping
          method: get